timestamp: 2016-12-15T13:57:08.088342
args: ['/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/bin/pants', 'export', '--formatted', '--export-libraries-sources', '--export-libraries-javadocs', './::', '--export-output-file=/private/var/folders/0x/5q90b4jx58n45_cv28m29w_80000gn/T/pants_depmap_run998.out']
pid: 28983
Exception caught: (<class 'pants.build_graph.build_graph.TransitiveLookupError'>)
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/bin/pants", line 11, in <module>
    sys.exit(main())
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/pants_exe.py", line 44, in main
    PantsRunner(exiter).run()
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/pants_runner.py", line 57, in run
    options_bootstrapper=options_bootstrapper)
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/pants_runner.py", line 46, in _run
    return LocalPantsRunner(exiter, args, env, options_bootstrapper=options_bootstrapper).run()
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/local_pants_runner.py", line 53, in run
    self._maybe_profiled(self._run)
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/local_pants_runner.py", line 50, in _maybe_profiled
    runner()
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/local_pants_runner.py", line 93, in _run
    self._exiter).setup()
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/goal_runner.py", line 205, in setup
    goals, context = self._setup_context()
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/goal_runner.py", line 181, in _setup_context
    target_roots = self._specs_to_targets(spec_roots)
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/goal_runner.py", line 160, in _specs_to_targets
    return list(generate_targets(specs))
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/goal_runner.py", line 155, in generate_targets
    for address in self._build_graph.inject_specs_closure(specs, self._fail_fast):
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/mutable_build_graph.py", line 100, in inject_specs_closure
    self.inject_address_closure(address)
  File "/Users/amadavan/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/mutable_build_graph.py", line 95, in inject_address_closure
    .format(message=e, spec=target_address.spec))

Exception message: /Users/amadavan/Downloads/tmp/distribute/3rdparty/jvm/junit does not contain any BUILD files.
  when translating spec 3rdparty/jvm/junit
  referenced from src/test/scala:scala

timestamp: 2016-12-20T17:30:39.988577
args: ['/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/bin/pants', 'export', '--formatted', '--export-libraries-sources', '--export-libraries-javadocs', './::', '--export-output-file=/private/var/folders/z4/mv_jyrdn3fl1hl8h0r6q6d0w0000gn/T/pants_depmap_run.out']
pid: 1569
Exception caught: (<class 'pants.build_graph.address_lookup_error.AddressLookupError'>)
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/bin/pants", line 11, in <module>
    sys.exit(main())
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/pants_exe.py", line 44, in main
    PantsRunner(exiter).run()
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/pants_runner.py", line 57, in run
    options_bootstrapper=options_bootstrapper)
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/pants_runner.py", line 46, in _run
    return LocalPantsRunner(exiter, args, env, options_bootstrapper=options_bootstrapper).run()
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/local_pants_runner.py", line 53, in run
    self._maybe_profiled(self._run)
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/local_pants_runner.py", line 50, in _maybe_profiled
    runner()
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/local_pants_runner.py", line 93, in _run
    self._exiter).setup()
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/goal_runner.py", line 185, in setup
    context, invalidation_report = self._setup_context()
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/goal_runner.py", line 163, in _setup_context
    self._expand_specs(self._target_specs, self._fail_fast)
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/bin/goal_runner.py", line 142, in _expand_specs
    for address in self._build_graph.inject_specs_closure(specs, fail_fast):
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/mutable_build_graph.py", line 99, in inject_specs_closure
    fail_fast=fail_fast):
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 242, in scan_specs
    for address in self._scan_spec(spec, fail_fast, exclude_spec):
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 287, in _scan_spec
    raise AddressLookupError(error_msg)

Exception message: --------------------
Traceback (most recent call last):
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 278, in _scan_spec
    addresses.update(self.addresses_in_spec_path(build_file.spec_path))
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 161, in addresses_in_spec_path
    return self._address_map_from_spec_path(spec_path).keys()
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 153, in _address_map_from_spec_path
    .format(message=e, spec_path=spec_path))
AddressLookupError: name 'page' is not defined
 while executing BUILD file BuildFile(BUILD, FileSystemProjectTree(/Users/ashwin/Documents/workspace/trunk))
 Loading addresses from '' failed.

Exception message: name 'page' is not defined
 while executing BUILD file BuildFile(BUILD, FileSystemProjectTree(/Users/ashwin/Documents/workspace/trunk))
 Loading addresses from '' failed.
--------------------
Traceback (most recent call last):
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 278, in _scan_spec
    addresses.update(self.addresses_in_spec_path(build_file.spec_path))
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 161, in addresses_in_spec_path
    return self._address_map_from_spec_path(spec_path).keys()
  File "/Users/ashwin/.cache/pants/setup/bootstrap-Darwin-x86_64/unspecified/lib/python2.7/site-packages/pants/build_graph/build_file_address_mapper.py", line 153, in _address_map_from_spec_path
    .format(message=e, spec_path=spec_path))
AddressLookupError: name 'page' is not defined
 while executing BUILD file BuildFile(BUILD, FileSystemProjectTree(/Users/ashwin/Documents/workspace/trunk))
 Loading addresses from '' failed.

Exception message: name 'page' is not defined
 while executing BUILD file BuildFile(BUILD, FileSystemProjectTree(/Users/ashwin/Documents/workspace/trunk))
 Loading addresses from '' failed.
Invalid BUILD files for [::]

